// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ilo5")
	ScopeName = "github.com/murasame29/opentelemetry-collector-ilo5-reciever"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
