// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for ilo5 metrics.
type MetricsConfig struct {
	IloFanSpeed             MetricConfig `mapstructure:"ilo.fan.speed"`
	IloPowerCapacity        MetricConfig `mapstructure:"ilo.power.capacity"`
	IloPowerConsumption     MetricConfig `mapstructure:"ilo.power.consumption"`
	IloPowerPsuHealth       MetricConfig `mapstructure:"ilo.power.psu.health"`
	IloPowerPsuInputVoltage MetricConfig `mapstructure:"ilo.power.psu.input_voltage"`
	IloPowerPsuOutput       MetricConfig `mapstructure:"ilo.power.psu.output"`
	IloPowerVoltage         MetricConfig `mapstructure:"ilo.power.voltage"`
	IloStorageDriveHealth   MetricConfig `mapstructure:"ilo.storage.drive.health"`
	IloSystemHealth         MetricConfig `mapstructure:"ilo.system.health"`
	IloSystemPowerState     MetricConfig `mapstructure:"ilo.system.power_state"`
	IloThermalTemperature   MetricConfig `mapstructure:"ilo.thermal.temperature"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		IloFanSpeed: MetricConfig{
			Enabled: true,
		},
		IloPowerCapacity: MetricConfig{
			Enabled: true,
		},
		IloPowerConsumption: MetricConfig{
			Enabled: true,
		},
		IloPowerPsuHealth: MetricConfig{
			Enabled: true,
		},
		IloPowerPsuInputVoltage: MetricConfig{
			Enabled: true,
		},
		IloPowerPsuOutput: MetricConfig{
			Enabled: true,
		},
		IloPowerVoltage: MetricConfig{
			Enabled: true,
		},
		IloStorageDriveHealth: MetricConfig{
			Enabled: true,
		},
		IloSystemHealth: MetricConfig{
			Enabled: true,
		},
		IloSystemPowerState: MetricConfig{
			Enabled: true,
		},
		IloThermalTemperature: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for ilo5 resource attributes.
type ResourceAttributesConfig struct {
	HostName           ResourceAttributeConfig `mapstructure:"host.name"`
	HostSerialNumber   ResourceAttributeConfig `mapstructure:"host.serial_number"`
	IloEndpoint        ResourceAttributeConfig `mapstructure:"ilo.endpoint"`
	IloFirmwareVersion ResourceAttributeConfig `mapstructure:"ilo.firmware.version"`
	IloModel           ResourceAttributeConfig `mapstructure:"ilo.model"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
		HostSerialNumber: ResourceAttributeConfig{
			Enabled: true,
		},
		IloEndpoint: ResourceAttributeConfig{
			Enabled: true,
		},
		IloFirmwareVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		IloModel: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for ilo5 metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
