// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetHostName("host.name-val")
			rb.SetHostSerialNumber("host.serial_number-val")
			rb.SetIloEndpoint("ilo.endpoint-val")
			rb.SetIloFirmwareVersion("ilo.firmware.version-val")
			rb.SetIloModel("ilo.model-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 5, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 5, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("host.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("host.serial_number")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.serial_number-val", val.Str())
			}
			val, ok = res.Attributes().Get("ilo.endpoint")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ilo.endpoint-val", val.Str())
			}
			val, ok = res.Attributes().Get("ilo.firmware.version")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ilo.firmware.version-val", val.Str())
			}
			val, ok = res.Attributes().Get("ilo.model")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ilo.model-val", val.Str())
			}
		})
	}
}
