// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetHostName sets provided value as "host.name" attribute.
func (rb *ResourceBuilder) SetHostName(val string) {
	if rb.config.HostName.Enabled {
		rb.res.Attributes().PutStr("host.name", val)
	}
}

// SetHostSerialNumber sets provided value as "host.serial_number" attribute.
func (rb *ResourceBuilder) SetHostSerialNumber(val string) {
	if rb.config.HostSerialNumber.Enabled {
		rb.res.Attributes().PutStr("host.serial_number", val)
	}
}

// SetIloEndpoint sets provided value as "ilo.endpoint" attribute.
func (rb *ResourceBuilder) SetIloEndpoint(val string) {
	if rb.config.IloEndpoint.Enabled {
		rb.res.Attributes().PutStr("ilo.endpoint", val)
	}
}

// SetIloFirmwareVersion sets provided value as "ilo.firmware.version" attribute.
func (rb *ResourceBuilder) SetIloFirmwareVersion(val string) {
	if rb.config.IloFirmwareVersion.Enabled {
		rb.res.Attributes().PutStr("ilo.firmware.version", val)
	}
}

// SetIloModel sets provided value as "ilo.model" attribute.
func (rb *ResourceBuilder) SetIloModel(val string) {
	if rb.config.IloModel.Enabled {
		rb.res.Attributes().PutStr("ilo.model", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
