// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloFanSpeedDataPoint(ts, 1, "chassis_id-val", "fan_name-val", "fan_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerCapacityDataPoint(ts, 1, "chassis_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerConsumptionDataPoint(ts, 1, "chassis_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerPsuHealthDataPoint(ts, 1, "chassis_id-val", "psu_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerPsuInputVoltageDataPoint(ts, 1, "chassis_id-val", "psu_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerPsuOutputDataPoint(ts, 1, "chassis_id-val", "psu_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloPowerVoltageDataPoint(ts, 1, "chassis_id-val", "psu_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloStorageDriveHealthDataPoint(ts, 1, "system_id-val", "controller_id-val", "drive_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloSystemHealthDataPoint(ts, 1, "system_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloSystemPowerStateDataPoint(ts, 1, "system_id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordIloThermalTemperatureDataPoint(ts, 1, "chassis_id-val", "sensor_name-val", "physical_context-val", 13, 13)

			rb := mb.NewResourceBuilder()
			rb.SetHostName("host.name-val")
			rb.SetHostSerialNumber("host.serial_number-val")
			rb.SetIloEndpoint("ilo.endpoint-val")
			rb.SetIloFirmwareVersion("ilo.firmware.version-val")
			rb.SetIloModel("ilo.model-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "ilo.fan.speed":
					assert.False(t, validatedMetrics["ilo.fan.speed"], "Found a duplicate in the metrics slice: ilo.fan.speed")
					validatedMetrics["ilo.fan.speed"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Fan speed percentage.", ms.At(i).Description())
					assert.Equal(t, "%", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("fan_name")
					assert.True(t, ok)
					assert.Equal(t, "fan_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("fan_id")
					assert.True(t, ok)
					assert.Equal(t, "fan_id-val", attrVal.Str())
				case "ilo.power.capacity":
					assert.False(t, validatedMetrics["ilo.power.capacity"], "Found a duplicate in the metrics slice: ilo.power.capacity")
					validatedMetrics["ilo.power.capacity"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Power capacity in Watts.", ms.At(i).Description())
					assert.Equal(t, "W", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
				case "ilo.power.consumption":
					assert.False(t, validatedMetrics["ilo.power.consumption"], "Found a duplicate in the metrics slice: ilo.power.consumption")
					validatedMetrics["ilo.power.consumption"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Current power consumption in Watts.", ms.At(i).Description())
					assert.Equal(t, "W", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
				case "ilo.power.psu.health":
					assert.False(t, validatedMetrics["ilo.power.psu.health"], "Found a duplicate in the metrics slice: ilo.power.psu.health")
					validatedMetrics["ilo.power.psu.health"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Power Supply Unit health (1=OK, 2=Warning, 3=Critical).", ms.At(i).Description())
					assert.Equal(t, "{status}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("psu_id")
					assert.True(t, ok)
					assert.Equal(t, "psu_id-val", attrVal.Str())
				case "ilo.power.psu.input_voltage":
					assert.False(t, validatedMetrics["ilo.power.psu.input_voltage"], "Found a duplicate in the metrics slice: ilo.power.psu.input_voltage")
					validatedMetrics["ilo.power.psu.input_voltage"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Power Supply Unit input line voltage.", ms.At(i).Description())
					assert.Equal(t, "V", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("psu_id")
					assert.True(t, ok)
					assert.Equal(t, "psu_id-val", attrVal.Str())
				case "ilo.power.psu.output":
					assert.False(t, validatedMetrics["ilo.power.psu.output"], "Found a duplicate in the metrics slice: ilo.power.psu.output")
					validatedMetrics["ilo.power.psu.output"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Power Supply Unit output power in Watts.", ms.At(i).Description())
					assert.Equal(t, "W", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("psu_id")
					assert.True(t, ok)
					assert.Equal(t, "psu_id-val", attrVal.Str())
				case "ilo.power.voltage":
					assert.False(t, validatedMetrics["ilo.power.voltage"], "Found a duplicate in the metrics slice: ilo.power.voltage")
					validatedMetrics["ilo.power.voltage"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Voltage reading in Volts.", ms.At(i).Description())
					assert.Equal(t, "V", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("psu_id")
					assert.True(t, ok)
					assert.Equal(t, "psu_id-val", attrVal.Str())
				case "ilo.storage.drive.health":
					assert.False(t, validatedMetrics["ilo.storage.drive.health"], "Found a duplicate in the metrics slice: ilo.storage.drive.health")
					validatedMetrics["ilo.storage.drive.health"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Drive Health Status (1=OK, 2=Warning, 3=Critical).", ms.At(i).Description())
					assert.Equal(t, "{status}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("system_id")
					assert.True(t, ok)
					assert.Equal(t, "system_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("controller_id")
					assert.True(t, ok)
					assert.Equal(t, "controller_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("drive_id")
					assert.True(t, ok)
					assert.Equal(t, "drive_id-val", attrVal.Str())
				case "ilo.system.health":
					assert.False(t, validatedMetrics["ilo.system.health"], "Found a duplicate in the metrics slice: ilo.system.health")
					validatedMetrics["ilo.system.health"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "System Health Status (1=OK, 2=Warning, 3=Critical).", ms.At(i).Description())
					assert.Equal(t, "{status}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("system_id")
					assert.True(t, ok)
					assert.Equal(t, "system_id-val", attrVal.Str())
				case "ilo.system.power_state":
					assert.False(t, validatedMetrics["ilo.system.power_state"], "Found a duplicate in the metrics slice: ilo.system.power_state")
					validatedMetrics["ilo.system.power_state"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "System Power State (1=On, 0=Off/Other).", ms.At(i).Description())
					assert.Equal(t, "{state}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("system_id")
					assert.True(t, ok)
					assert.Equal(t, "system_id-val", attrVal.Str())
				case "ilo.thermal.temperature":
					assert.False(t, validatedMetrics["ilo.thermal.temperature"], "Found a duplicate in the metrics slice: ilo.thermal.temperature")
					validatedMetrics["ilo.thermal.temperature"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Temperature reading in Celsius.", ms.At(i).Description())
					assert.Equal(t, "Cel", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("chassis_id")
					assert.True(t, ok)
					assert.Equal(t, "chassis_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("sensor_name")
					assert.True(t, ok)
					assert.Equal(t, "sensor_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("physical_context")
					assert.True(t, ok)
					assert.Equal(t, "physical_context-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("location_x_mm")
					assert.True(t, ok)
					assert.EqualValues(t, 13, attrVal.Int())
					attrVal, ok = dp.Attributes().Get("location_y_mm")
					assert.True(t, ok)
					assert.EqualValues(t, 13, attrVal.Int())
				}
			}
		})
	}
}
