// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	conventions "go.opentelemetry.io/otel/semconv/v1.27.0"
)

var MetricsInfo = metricsInfo{
	IloFanSpeed: metricInfo{
		Name: "ilo.fan.speed",
	},
	IloPowerCapacity: metricInfo{
		Name: "ilo.power.capacity",
	},
	IloPowerConsumption: metricInfo{
		Name: "ilo.power.consumption",
	},
	IloPowerPsuHealth: metricInfo{
		Name: "ilo.power.psu.health",
	},
	IloPowerPsuInputVoltage: metricInfo{
		Name: "ilo.power.psu.input_voltage",
	},
	IloPowerPsuOutput: metricInfo{
		Name: "ilo.power.psu.output",
	},
	IloPowerVoltage: metricInfo{
		Name: "ilo.power.voltage",
	},
	IloStorageDriveHealth: metricInfo{
		Name: "ilo.storage.drive.health",
	},
	IloSystemHealth: metricInfo{
		Name: "ilo.system.health",
	},
	IloSystemPowerState: metricInfo{
		Name: "ilo.system.power_state",
	},
	IloThermalTemperature: metricInfo{
		Name: "ilo.thermal.temperature",
	},
}

type metricsInfo struct {
	IloFanSpeed             metricInfo
	IloPowerCapacity        metricInfo
	IloPowerConsumption     metricInfo
	IloPowerPsuHealth       metricInfo
	IloPowerPsuInputVoltage metricInfo
	IloPowerPsuOutput       metricInfo
	IloPowerVoltage         metricInfo
	IloStorageDriveHealth   metricInfo
	IloSystemHealth         metricInfo
	IloSystemPowerState     metricInfo
	IloThermalTemperature   metricInfo
}

type metricInfo struct {
	Name string
}

type metricIloFanSpeed struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.fan.speed metric with initial data.
func (m *metricIloFanSpeed) init() {
	m.data.SetName("ilo.fan.speed")
	m.data.SetDescription("Fan speed percentage.")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloFanSpeed) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, fanNameAttributeValue string, fanIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("fan_name", fanNameAttributeValue)
	dp.Attributes().PutStr("fan_id", fanIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloFanSpeed) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloFanSpeed) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloFanSpeed(cfg MetricConfig) metricIloFanSpeed {
	m := metricIloFanSpeed{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerCapacity struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.capacity metric with initial data.
func (m *metricIloPowerCapacity) init() {
	m.data.SetName("ilo.power.capacity")
	m.data.SetDescription("Power capacity in Watts.")
	m.data.SetUnit("W")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerCapacity) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerCapacity) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerCapacity) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerCapacity(cfg MetricConfig) metricIloPowerCapacity {
	m := metricIloPowerCapacity{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerConsumption struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.consumption metric with initial data.
func (m *metricIloPowerConsumption) init() {
	m.data.SetName("ilo.power.consumption")
	m.data.SetDescription("Current power consumption in Watts.")
	m.data.SetUnit("W")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerConsumption) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerConsumption) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerConsumption) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerConsumption(cfg MetricConfig) metricIloPowerConsumption {
	m := metricIloPowerConsumption{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerPsuHealth struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.psu.health metric with initial data.
func (m *metricIloPowerPsuHealth) init() {
	m.data.SetName("ilo.power.psu.health")
	m.data.SetDescription("Power Supply Unit health (1=OK, 2=Warning, 3=Critical).")
	m.data.SetUnit("{status}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerPsuHealth) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("psu_id", psuIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerPsuHealth) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerPsuHealth) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerPsuHealth(cfg MetricConfig) metricIloPowerPsuHealth {
	m := metricIloPowerPsuHealth{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerPsuInputVoltage struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.psu.input_voltage metric with initial data.
func (m *metricIloPowerPsuInputVoltage) init() {
	m.data.SetName("ilo.power.psu.input_voltage")
	m.data.SetDescription("Power Supply Unit input line voltage.")
	m.data.SetUnit("V")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerPsuInputVoltage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("psu_id", psuIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerPsuInputVoltage) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerPsuInputVoltage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerPsuInputVoltage(cfg MetricConfig) metricIloPowerPsuInputVoltage {
	m := metricIloPowerPsuInputVoltage{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerPsuOutput struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.psu.output metric with initial data.
func (m *metricIloPowerPsuOutput) init() {
	m.data.SetName("ilo.power.psu.output")
	m.data.SetDescription("Power Supply Unit output power in Watts.")
	m.data.SetUnit("W")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerPsuOutput) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("psu_id", psuIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerPsuOutput) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerPsuOutput) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerPsuOutput(cfg MetricConfig) metricIloPowerPsuOutput {
	m := metricIloPowerPsuOutput{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloPowerVoltage struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.power.voltage metric with initial data.
func (m *metricIloPowerVoltage) init() {
	m.data.SetName("ilo.power.voltage")
	m.data.SetDescription("Voltage reading in Volts.")
	m.data.SetUnit("V")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloPowerVoltage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("psu_id", psuIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloPowerVoltage) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloPowerVoltage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloPowerVoltage(cfg MetricConfig) metricIloPowerVoltage {
	m := metricIloPowerVoltage{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloStorageDriveHealth struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.storage.drive.health metric with initial data.
func (m *metricIloStorageDriveHealth) init() {
	m.data.SetName("ilo.storage.drive.health")
	m.data.SetDescription("Drive Health Status (1=OK, 2=Warning, 3=Critical).")
	m.data.SetUnit("{status}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloStorageDriveHealth) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, systemIDAttributeValue string, controllerIDAttributeValue string, driveIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("system_id", systemIDAttributeValue)
	dp.Attributes().PutStr("controller_id", controllerIDAttributeValue)
	dp.Attributes().PutStr("drive_id", driveIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloStorageDriveHealth) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloStorageDriveHealth) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloStorageDriveHealth(cfg MetricConfig) metricIloStorageDriveHealth {
	m := metricIloStorageDriveHealth{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloSystemHealth struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.system.health metric with initial data.
func (m *metricIloSystemHealth) init() {
	m.data.SetName("ilo.system.health")
	m.data.SetDescription("System Health Status (1=OK, 2=Warning, 3=Critical).")
	m.data.SetUnit("{status}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloSystemHealth) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, systemIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("system_id", systemIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloSystemHealth) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloSystemHealth) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloSystemHealth(cfg MetricConfig) metricIloSystemHealth {
	m := metricIloSystemHealth{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloSystemPowerState struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.system.power_state metric with initial data.
func (m *metricIloSystemPowerState) init() {
	m.data.SetName("ilo.system.power_state")
	m.data.SetDescription("System Power State (1=On, 0=Off/Other).")
	m.data.SetUnit("{state}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloSystemPowerState) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, systemIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("system_id", systemIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloSystemPowerState) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloSystemPowerState) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloSystemPowerState(cfg MetricConfig) metricIloSystemPowerState {
	m := metricIloSystemPowerState{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricIloThermalTemperature struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills ilo.thermal.temperature metric with initial data.
func (m *metricIloThermalTemperature) init() {
	m.data.SetName("ilo.thermal.temperature")
	m.data.SetDescription("Temperature reading in Celsius.")
	m.data.SetUnit("Cel")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricIloThermalTemperature) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, sensorNameAttributeValue string, physicalContextAttributeValue string, locationXMmAttributeValue int64, locationYMmAttributeValue int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chassis_id", chassisIDAttributeValue)
	dp.Attributes().PutStr("sensor_name", sensorNameAttributeValue)
	dp.Attributes().PutStr("physical_context", physicalContextAttributeValue)
	dp.Attributes().PutInt("location_x_mm", locationXMmAttributeValue)
	dp.Attributes().PutInt("location_y_mm", locationYMmAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricIloThermalTemperature) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricIloThermalTemperature) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricIloThermalTemperature(cfg MetricConfig) metricIloThermalTemperature {
	m := metricIloThermalTemperature{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricIloFanSpeed              metricIloFanSpeed
	metricIloPowerCapacity         metricIloPowerCapacity
	metricIloPowerConsumption      metricIloPowerConsumption
	metricIloPowerPsuHealth        metricIloPowerPsuHealth
	metricIloPowerPsuInputVoltage  metricIloPowerPsuInputVoltage
	metricIloPowerPsuOutput        metricIloPowerPsuOutput
	metricIloPowerVoltage          metricIloPowerVoltage
	metricIloStorageDriveHealth    metricIloStorageDriveHealth
	metricIloSystemHealth          metricIloSystemHealth
	metricIloSystemPowerState      metricIloSystemPowerState
	metricIloThermalTemperature    metricIloThermalTemperature
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricIloFanSpeed:              newMetricIloFanSpeed(mbc.Metrics.IloFanSpeed),
		metricIloPowerCapacity:         newMetricIloPowerCapacity(mbc.Metrics.IloPowerCapacity),
		metricIloPowerConsumption:      newMetricIloPowerConsumption(mbc.Metrics.IloPowerConsumption),
		metricIloPowerPsuHealth:        newMetricIloPowerPsuHealth(mbc.Metrics.IloPowerPsuHealth),
		metricIloPowerPsuInputVoltage:  newMetricIloPowerPsuInputVoltage(mbc.Metrics.IloPowerPsuInputVoltage),
		metricIloPowerPsuOutput:        newMetricIloPowerPsuOutput(mbc.Metrics.IloPowerPsuOutput),
		metricIloPowerVoltage:          newMetricIloPowerVoltage(mbc.Metrics.IloPowerVoltage),
		metricIloStorageDriveHealth:    newMetricIloStorageDriveHealth(mbc.Metrics.IloStorageDriveHealth),
		metricIloSystemHealth:          newMetricIloSystemHealth(mbc.Metrics.IloSystemHealth),
		metricIloSystemPowerState:      newMetricIloSystemPowerState(mbc.Metrics.IloSystemPowerState),
		metricIloThermalTemperature:    newMetricIloThermalTemperature(mbc.Metrics.IloThermalTemperature),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.HostName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["host.name"] = filter.CreateFilter(mbc.ResourceAttributes.HostName.MetricsInclude)
	}
	if mbc.ResourceAttributes.HostName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["host.name"] = filter.CreateFilter(mbc.ResourceAttributes.HostName.MetricsExclude)
	}
	if mbc.ResourceAttributes.HostSerialNumber.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["host.serial_number"] = filter.CreateFilter(mbc.ResourceAttributes.HostSerialNumber.MetricsInclude)
	}
	if mbc.ResourceAttributes.HostSerialNumber.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["host.serial_number"] = filter.CreateFilter(mbc.ResourceAttributes.HostSerialNumber.MetricsExclude)
	}
	if mbc.ResourceAttributes.IloEndpoint.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ilo.endpoint"] = filter.CreateFilter(mbc.ResourceAttributes.IloEndpoint.MetricsInclude)
	}
	if mbc.ResourceAttributes.IloEndpoint.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ilo.endpoint"] = filter.CreateFilter(mbc.ResourceAttributes.IloEndpoint.MetricsExclude)
	}
	if mbc.ResourceAttributes.IloFirmwareVersion.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ilo.firmware.version"] = filter.CreateFilter(mbc.ResourceAttributes.IloFirmwareVersion.MetricsInclude)
	}
	if mbc.ResourceAttributes.IloFirmwareVersion.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ilo.firmware.version"] = filter.CreateFilter(mbc.ResourceAttributes.IloFirmwareVersion.MetricsExclude)
	}
	if mbc.ResourceAttributes.IloModel.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ilo.model"] = filter.CreateFilter(mbc.ResourceAttributes.IloModel.MetricsInclude)
	}
	if mbc.ResourceAttributes.IloModel.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ilo.model"] = filter.CreateFilter(mbc.ResourceAttributes.IloModel.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	rm.SetSchemaUrl(conventions.SchemaURL)
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricIloFanSpeed.emit(ils.Metrics())
	mb.metricIloPowerCapacity.emit(ils.Metrics())
	mb.metricIloPowerConsumption.emit(ils.Metrics())
	mb.metricIloPowerPsuHealth.emit(ils.Metrics())
	mb.metricIloPowerPsuInputVoltage.emit(ils.Metrics())
	mb.metricIloPowerPsuOutput.emit(ils.Metrics())
	mb.metricIloPowerVoltage.emit(ils.Metrics())
	mb.metricIloStorageDriveHealth.emit(ils.Metrics())
	mb.metricIloSystemHealth.emit(ils.Metrics())
	mb.metricIloSystemPowerState.emit(ils.Metrics())
	mb.metricIloThermalTemperature.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordIloFanSpeedDataPoint adds a data point to ilo.fan.speed metric.
func (mb *MetricsBuilder) RecordIloFanSpeedDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, fanNameAttributeValue string, fanIDAttributeValue string) {
	mb.metricIloFanSpeed.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, fanNameAttributeValue, fanIDAttributeValue)
}

// RecordIloPowerCapacityDataPoint adds a data point to ilo.power.capacity metric.
func (mb *MetricsBuilder) RecordIloPowerCapacityDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string) {
	mb.metricIloPowerCapacity.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue)
}

// RecordIloPowerConsumptionDataPoint adds a data point to ilo.power.consumption metric.
func (mb *MetricsBuilder) RecordIloPowerConsumptionDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string) {
	mb.metricIloPowerConsumption.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue)
}

// RecordIloPowerPsuHealthDataPoint adds a data point to ilo.power.psu.health metric.
func (mb *MetricsBuilder) RecordIloPowerPsuHealthDataPoint(ts pcommon.Timestamp, val int64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	mb.metricIloPowerPsuHealth.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, psuIDAttributeValue)
}

// RecordIloPowerPsuInputVoltageDataPoint adds a data point to ilo.power.psu.input_voltage metric.
func (mb *MetricsBuilder) RecordIloPowerPsuInputVoltageDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	mb.metricIloPowerPsuInputVoltage.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, psuIDAttributeValue)
}

// RecordIloPowerPsuOutputDataPoint adds a data point to ilo.power.psu.output metric.
func (mb *MetricsBuilder) RecordIloPowerPsuOutputDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	mb.metricIloPowerPsuOutput.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, psuIDAttributeValue)
}

// RecordIloPowerVoltageDataPoint adds a data point to ilo.power.voltage metric.
func (mb *MetricsBuilder) RecordIloPowerVoltageDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, psuIDAttributeValue string) {
	mb.metricIloPowerVoltage.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, psuIDAttributeValue)
}

// RecordIloStorageDriveHealthDataPoint adds a data point to ilo.storage.drive.health metric.
func (mb *MetricsBuilder) RecordIloStorageDriveHealthDataPoint(ts pcommon.Timestamp, val int64, systemIDAttributeValue string, controllerIDAttributeValue string, driveIDAttributeValue string) {
	mb.metricIloStorageDriveHealth.recordDataPoint(mb.startTime, ts, val, systemIDAttributeValue, controllerIDAttributeValue, driveIDAttributeValue)
}

// RecordIloSystemHealthDataPoint adds a data point to ilo.system.health metric.
func (mb *MetricsBuilder) RecordIloSystemHealthDataPoint(ts pcommon.Timestamp, val int64, systemIDAttributeValue string) {
	mb.metricIloSystemHealth.recordDataPoint(mb.startTime, ts, val, systemIDAttributeValue)
}

// RecordIloSystemPowerStateDataPoint adds a data point to ilo.system.power_state metric.
func (mb *MetricsBuilder) RecordIloSystemPowerStateDataPoint(ts pcommon.Timestamp, val int64, systemIDAttributeValue string) {
	mb.metricIloSystemPowerState.recordDataPoint(mb.startTime, ts, val, systemIDAttributeValue)
}

// RecordIloThermalTemperatureDataPoint adds a data point to ilo.thermal.temperature metric.
func (mb *MetricsBuilder) RecordIloThermalTemperatureDataPoint(ts pcommon.Timestamp, val float64, chassisIDAttributeValue string, sensorNameAttributeValue string, physicalContextAttributeValue string, locationXMmAttributeValue int64, locationYMmAttributeValue int64) {
	mb.metricIloThermalTemperature.recordDataPoint(mb.startTime, ts, val, chassisIDAttributeValue, sensorNameAttributeValue, physicalContextAttributeValue, locationXMmAttributeValue, locationYMmAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
