// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IloFanSpeed:             MetricConfig{Enabled: true},
					IloPowerCapacity:        MetricConfig{Enabled: true},
					IloPowerConsumption:     MetricConfig{Enabled: true},
					IloPowerPsuOutput:       MetricConfig{Enabled: true},
					IloPowerPsuInputVoltage: MetricConfig{Enabled: true},
					IloPowerPsuHealth:       MetricConfig{Enabled: true},
					IloPowerVoltage:         MetricConfig{Enabled: true},
					IloStorageDriveHealth:   MetricConfig{Enabled: true},
					IloSystemHealth:         MetricConfig{Enabled: true},
					IloSystemPowerState:     MetricConfig{Enabled: true},
					IloThermalTemperature:   MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName:           ResourceAttributeConfig{Enabled: true},
					HostSerialNumber:   ResourceAttributeConfig{Enabled: true},
					IloEndpoint:        ResourceAttributeConfig{Enabled: true},
					IloFirmwareVersion: ResourceAttributeConfig{Enabled: true},
					IloModel:           ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IloFanSpeed:             MetricConfig{Enabled: false},
					IloPowerCapacity:        MetricConfig{Enabled: false},
					IloPowerConsumption:     MetricConfig{Enabled: false},
					IloPowerPsuOutput:       MetricConfig{Enabled: false},
					IloPowerPsuInputVoltage: MetricConfig{Enabled: false},
					IloPowerPsuHealth:       MetricConfig{Enabled: false},
					IloPowerVoltage:         MetricConfig{Enabled: false},
					IloStorageDriveHealth:   MetricConfig{Enabled: false},
					IloSystemHealth:         MetricConfig{Enabled: false},
					IloSystemPowerState:     MetricConfig{Enabled: false},
					IloThermalTemperature:   MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName:           ResourceAttributeConfig{Enabled: false},
					HostSerialNumber:   ResourceAttributeConfig{Enabled: false},
					IloEndpoint:        ResourceAttributeConfig{Enabled: false},
					IloFirmwareVersion: ResourceAttributeConfig{Enabled: false},
					IloModel:           ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				HostName:           ResourceAttributeConfig{Enabled: true},
				HostSerialNumber:   ResourceAttributeConfig{Enabled: true},
				IloEndpoint:        ResourceAttributeConfig{Enabled: true},
				IloFirmwareVersion: ResourceAttributeConfig{Enabled: true},
				IloModel:           ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				HostName:           ResourceAttributeConfig{Enabled: false},
				HostSerialNumber:   ResourceAttributeConfig{Enabled: false},
				IloEndpoint:        ResourceAttributeConfig{Enabled: false},
				IloFirmwareVersion: ResourceAttributeConfig{Enabled: false},
				IloModel:           ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
